apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prom
  namespace: preview-advertisers-9510
spec:
  minReplicaCount: 1
  fallback:
    failureThreshold: 1
    replicas: 3
  scaleTargetRef:
    name: api-user
  advanced:
    horizontalPodAutoscalerConfig:
      name: api-user
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 0
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: https://thanos-monitoring.internal.stage.europe-west4.interface.trv.cloud
        threshold: "3"
        query: sum(federate:istio_requests_total:rate1m{cluster="interface",destination_workload_namespace="preview-advertisers-9510"})
