apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfconsumer
spec:
  selector:
    matchLabels:
      app: kfconsumer
  template:
    metadata:
      labels:
        app: kfconsumer
    spec:
      containers:
      - name: kfconsumer
        image: rminz/kafka-keda-consumer:v1
        command: ["/app/consumer", "-brokers", "192.168.194.173:9092"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

