apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-auth
spec:
  secretTargetRef:
  - parameter: username
    name: redis01-redis-account-default
    key: username
  - parameter: password
    name: redis01-redis-account-default
    key: password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rdconsumer
spec:
  scaleTargetRef:
    name: rdconsumer
  pollingInterval: 10
  cooldownPeriod: 30
  triggers:
  - type: redis
    metadata:
      address: 192.168.194.188:6379
      listName: usernames
      listLength: "5"
    authenticationRef:
      name: redis-auth
